# Generated by Django 6.0.3 on 2026-04-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
