# Generated by Django 6.0.2 on 2026-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
