# Generated by Django 6.0.2 on 2026-04-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_servicio_barrio_servicio_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='descripcion_trabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='barrio',
            field=models.CharField(default='Sin especificar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='localidad',
            field=models.CharField(default='Sin especificar', max_length=100),
            preserve_default=False,
        ),
    ]
